import type { SlashRouter } from "../slash-router.js";
import type { SessionContext } from "../../types/repl.js";
import { helpCommand } from "./help.js";
import { clearCommand } from "./clear.js";
import { exitCommand } from "./exit.js";
import { statusCommand } from "./status.js";
import { contextCommand } from "./context.js";
import { memoryCommand } from "./memory.js";
import { askCommand } from "./ask.js";
import { initCommand } from "./init.js";
import { doctorCommand } from "./doctor.js";
import { pullCommand } from "./pull.js";
import { terminalSetupCommand } from "./terminal-setup.js";
import { flowCommand } from "./flow.js";
import { flowsCommand } from "./flows.js";
import { logCommand } from "./log.js";
import { pendingCommand } from "./pending.js";
import { approveCommand } from "./approve.js";
import { checkoutCommand } from "./checkout.js";
import { compactCommand } from "./compact.js";
import { historyCommand } from "./history.js";
import { structureCommand } from "./structure.js";
import { skillCommand } from "./skill.js";
import { createCommand } from "./create.js";
import { tokenCommand } from "./token.js";
import { bugCommand } from "./bug.js";
import { keybindingsHelpCommand, keysCommand } from "./keybindings-help.js";
import { auditCommand } from "./audit.js";
import { analyzeCommand } from "./analyze.js";
import { explainCommand } from "./explain.js";
import { usageCommand } from "./usage.js";

export function registerAllCommands(router: SlashRouter, ctx: SessionContext): void {
  router.register(helpCommand(router));
  router.register(clearCommand());
  router.register(exitCommand());
  router.register(statusCommand());
  router.register(contextCommand());
  router.register(memoryCommand());
  router.register(askCommand());
  router.register(initCommand());
  router.register(doctorCommand());
  router.register(pullCommand());
  router.register(terminalSetupCommand());
  router.register(flowCommand());
  router.register(flowsCommand());
  router.register(logCommand());
  router.register(pendingCommand());
  router.register(approveCommand());
  router.register(checkoutCommand());
  router.register(compactCommand());
  router.register(historyCommand());
  router.register(structureCommand());
  router.register(skillCommand());
  router.register(createCommand());
  router.register(tokenCommand());
  router.register(bugCommand());
  router.register(keybindingsHelpCommand());
  router.register(keysCommand());
  router.register(auditCommand());
  router.register(analyzeCommand());
  router.register(explainCommand());
  router.register(usageCommand());
}
